README.md
airsenal/framework/bpl_interface.py
airsenal/framework/data_fetcher.py
airsenal/scripts/fill_db_init.py

Implements changes to FPL API URLs. 
Please verify that `setup_airsenal_database`, `update_airsenal_database`, `run_airsenal_predictions` and `run_airsenal_optimization` work for you after these changes (and that they give you errors with the current master).
@nbarlowATI I have also commented line 38 of `airsenal/framework/bpl_interface.py`, which was:
`df_past = df_past[df_past["date"] > "2016-08-01"`
This was throwing a type comparison error between string and datetime. Do you know why this was in there and was it needed (and if it is needed does the date need to be updated)?
Closes #69

Fix FPL API URLs

---

airsenal/framework/prediction_utils.py
airsenal/framework/utils.py

Closes #71 
This fixes the bug with expected points I believe, though we may want to make further improvements (for this week only minutes played in GW1 will be used for predicting future minutes, might want to fold in last season's average minutes as well). See #71 for details. 
I'm running the calculations now so will have new results in the morning 🙂

Fix get_recent_minutes_for_player

---

.travis.yml
README.md
requirements.txt
setup.py

I've put `bpl` on pypi now, so I have simplified the installation of airsenal as a consequence. I also modified the travis config to run the tests on 3.7 as well as 3.6.

Simplify install

---

airsenal/framework/prediction_utils.py

`recent_minutes` contains the number of minutes that player played for
in the past few matches.
If these are all zero, we will for sure predict zero points for this
player, so we don't need to call all the functions to calculate
appearance points, defending points, attacking points.
modified:   airsenal/framework/prediction_utils.py
Closes #103

Adding conditional to check for sum of recent mins

---

airsenal/framework/team.py

This adds the function `get_sale_price(self, player_id)` to the `Team` class, which calculates the sale price for a player based on the difference between the player's "team" price (i.e. purchase price from the transactions table) and actual current price (i.e. price from the players table in the database).
Intended to fix the problem of unaffordable transfers being suggested, see #113 for more details. It works for me now but I'm not sure how this was meant to be working before - maybe we can have a look together in the hack session on Wednesday @nbarlowATI.
Closes #113

add method to calculate player sale price

---

airsenal/framework/team.py
airsenal/tests/test_team.py

Quick fix that adds a function to calculate the sale price to the team class. To get the current price for a player tries these 3 options (in decreasing order of likelihood of being correct!):
1) The API
2) The Database
3) The purchase price
To get the tests to work I've made using the API optional. Before we had a dummy player with id 1, which corresponds to Mustafi this season so the remove_player budget test wasn't working due to getting Mustafi's price back not the dummy players. We should fix this properly in the future.

Fix calculation of the sale price again

---

airsenal/framework/utils.py
airsenal/scripts/fill_predictedscore_table.py

Small change to add a function that prints the players with the top 10 predicted points after doing `run_airsenal_predictions`. Function added is `framework.utils.get_top_predicted_points`.
Output is like this:
```
==================================================
PREDICTED TOP 10 PLAYERS FOR GAMEWEEK(S) [13, 14, 15]:
==================================================
1. Pierre-Emerick Aubameyang, 17.68pts
2. Mohamed Salah, 17.18pts
3. Sadio Mané, 16.38pts
4. Raheem Sterling, 15.52pts
5. Heung-Min Son, 15.48pts
6. Tammy Abraham, 14.76pts
7. Anthony Martial, 14.56pts
8. Alexandre Lacazette, 13.99pts
9. Bamidele Alli, 13.76pts
10. Roberto Firmino, 13.70pts
```

print players with top predicted points

---

airsenal/framework/utils.py

2018 was previously hardcoded as the year to add to the day and month strings returned by the API for player injury/suspension return dates. Now infer the correct year by using the dateparser setting to prefer picking dates in the future (e.g. if today is 1st December 2019, and return string is "15 Jan", dateparser will pick 15th January 2020, not the default of 15th January 2019). This also fixes errors related to trying to create 29th February in non-leap years.

Fix date parsing in get_return_gameweek_for_player

---

README.md
airsenal/scripts/run_airsenal_pipeline.sh
setup.py

1. Updated the `entry_points` dict in `setup.py` to match the naming suggested in #202 
- `airsenal_setup_initial_db`
- `airsenal_update_db`
- `airsenal_dump_db`
- `airsenal_check_data`
- `airsenal_make_team`
- `airsenal_run_prediction`
- `airsenal_run_optimization`
- `airsenal_plot`
2. Updated `run_airsenal_pipeline.sh` to match the renaming 
3. Made changes to the `README.md` to match the renamed entry points 
- Closes #202 : Make all entrypoints start with "airsenal" 
@nbarlowATI - I've made the changes that hopefully fix the issue. Would appreciate any feedback since it's my first contribution. I tried to follow the guidelines but feel free to point out if I missed something.

[Ready for review] Rename entry points to start with "airsenal"

---

requirements.txt

Fixes #235 
Allow click above 7.0 so that black package can run

Update requirements.txt to allow Click > 7.0

---

airsenal/framework/transaction_utils.py

FPL API doesn't store any gameweek 1 information for players with blank gameweek 1, which caused filling the initial team in the database to fail if the squad contained any of those players. To determine the gameweek 1 price for those players use the current price and the total price change for the season (both available from the API).

[#244] Fix missing price for players with blank gameweek 1

---

airsenal/framework/data_fetcher.py

Add a try/except to `get_gameweek_data_for_player` with some wait/retry logic to mitigate possible ConnectionErrors when querying the FPL API for player detail data.

add wait/retry when getting player detail data from API

---

airsenal/framework/prediction_utils.py

Changes the use of pandas in `get_player_history_df`, making that function much faster (only takes a few seconds rather than several minutes). Before these change `airsenal_run_prediction --num_thread 4` takes 7 mins 50 seconds on my laptop, after the changes it takes 4 mins 20 seconds.
Relates to #143 and #169

Speedup get_player_history_df

---

.travis.yml

Issue: #285 
This add should allow forks to run tests correctly. Setting the environment variable in the travis file.
As suggested by: @jack89roberts 
The only drawback is that it use the AIrsenal's ID for running the test and needs to be updated every year.

Using environment variables for travis builds

---

airsenal/framework/transaction_utils.py
airsenal/framework/utils.py

In `fill_initial_team`, rather than assuming that the first gw for the squad is gw 1, we now have a `while` loop that is broken out of when `get_players_for_gameweek` returns a non-empty list.
Closes #273

add a loop to deal with situation where FPL squad was entered after gw 1

---

airsenal/framework/data_fetcher.py

If FPL_LOGIN and FPL_PASSWORD are not found in `airsenal/data/` files or environment variables, prompt the user for them when accessing mini-league data from the API, and also offer the user the option to store them for future use.
Closes #268

prompt the user for FPL login and password

---

airsenal/framework/optimization_utils.py
airsenal/scripts/fill_transfersuggestion_table.py

Points from triple captain or bench boost with no transfers not included in total in optimisation.
~Add missing `bench_boost` and `triple_captain` flags for calculating points in optimisation when no transfers made in a gameweek. Plus slight tidy up of setting the `strat_dict["cards_played"]` value.~
Delete separate treatment of no transfer strategies in `fill_transfersuggestion_table.optimize` and rely on `optimization_utils.make_best_transfers` to do it instead.

Fix points for triple captain/bench boost + no transfers

---

airsenal/framework/prediction_utils.py
airsenal/scripts/fill_predictedscore_table.py

Make it possible to run the prediction on N threads instead of one per position (maximum of 4, of which the goalkeeper and forward threads finish much earlier than the defender and midfielder threads).
Currently:
- Fit all the models single-threaded first
- Then add all players to the multiprocessing queue individually.
On my laptop reduces the prediction time from about 5 mins 15 secs to 2 mins 45 secs. Might be able to knock off another ~20 seconds if the model fitting can be done in parallel too. Not a big deal individually but will add up if we start trying to replay whole seasons.

Run prediction on N threads

---

airsenal/framework/prediction_utils.py

As per title - previously we always used recent minutes from the last 3 matches. Now use the same number of matches that we're predicting for (so if we're predicting for 5 matches, do it based on the minutes a player played in their last 5 matches).

Default to using recent minutes from same number of matches we're predicting for

---

airsenal/framework/prediction_utils.py
airsenal/framework/schema.py
airsenal/framework/utils.py
airsenal/scripts/fill_player_attributes_table.py
airsenal/tests/test_attributes.py

Add the current injury/suspension status and expected return gameweek to the database (attributes table). Move `is_injured_or_suspended` function to the `Player` class. Get the current value for the fields for all players when running `airsenal_setup_initial_db` and `airsenal_update_db`.
For #159

Add injury status and return gameweek to the database

---

airsenal/framework/db_config.py
airsenal/scripts/airsenal_run_pipeline.py

Changes to make it easier to run AIrsenal with a persistent database rather than a temporary one:
- Add environment variables or config files to specify database location.
- Make `airsenal_run_pipeline` only update the database by default, rather than deleting and recreating. Added `--clean` argument for delete/recreate behaviour (and initial setup will be run if database file doesn't exist or the `Team` table is empty).

Persistent AIrsenal database

---

.gitignore
README.md
airsenal/framework/db_config.py
airsenal/framework/optimization_utils.py
airsenal/framework/player.py
airsenal/framework/prediction_utils.py
airsenal/framework/schema.py
airsenal/framework/squad.py
airsenal/framework/transaction_utils.py
airsenal/framework/utils.py
airsenal/scripts/airsenal_run_pipeline.py
airsenal/scripts/data_sanity_checks.py
airsenal/scripts/fill_fixture_table.py
airsenal/scripts/fill_player_attributes_table.py
airsenal/scripts/fill_player_table.py
airsenal/scripts/fill_playerscore_table.py
airsenal/scripts/fill_result_table.py
airsenal/scripts/update_db.py

To make it possible to have a persistent database:
- Add fixture updates to `airsenal_update_db` (for #338)
- Fix some logic around updating pre-existing rows and free hit transfers, and skip errors due to duplicate player names.
- Make `airsenal_update_db` faster by modifying `get_gameweek_by_date` to filter fixtures by season and adding a LRU cache (same as the previous contribution to make the optimisation much faster).
- Make it possible to specify the database location in config files.
- Make `airsenal_run_pipeline` only update the database by default (not delete and recreate). Add `--clean` argument to delete and recreate if desired.
-  Fix logic for finding the last gameweek we have all results for.
- Check for pre-existing rows in db when updating match results and player scores. …

Fixes and improvements to database updates

---

environment.yml
pyproject.toml
requirements.txt

The version of pystan on pypi just changed to 3.x, which has breaking changes. In order to avoid them, this PR pins the pystan version in requirements.txt to the most recent 2.x.
**Question**: I've set the base branch as develop, but since this is a hotfix, should I change it to master?

Fix pystan version

---

airsenal/scripts/fill_transfersuggestion_table.py

Use "warnings" module to filter out and suppress the warnings from tqdm about "clamping fraction to be between 0 and 1" that would interfere with the display of progress bars when running the optimization.

suppress warnings from TQDM that mess up progress bars

---

airsenal/scripts/fill_transfersuggestion_table.py

This works at least on my Python 3.9 setup on M1 silicon MacBook.
Please verify on earlier Python versions.
I noticed that after running
`airsenal_run_optimization --weeks_ahead 3`
and completing the task, the status bar is not correctly refreshed.
Upon running one can see multiple status bars and follow progress, but after completion I get this:
Total progress:   7%|██                          | 1/14 [01:20<17:21, 80.14s/it]

multiprocessing fix

---

airsenal/framework/player_model.py

See #412 . Surprisingly doesn't seem to change the results much, at least after a quick glance.

Missing divide by 90 in player model

---

airsenal/framework/data_fetcher.py
airsenal/framework/utils.py
airsenal/scripts/fill_transfersuggestion_table.py

Added support for optionally sending the output from AIrsenal optimisation to a [discord webhook](https://discord.com/developers/docs/resources/webhook) #403. Uses the env variable or data file DISCORD_WEBHOOK which should contain the discord web hook URL as generated.  
Tested and working with Discord version: 1.0.9002 (08/09/2021)
Tested with a valid webhook url, an invalid url and no environment variable set.

Discord web-hook development #403

---

airsenal/scripts/fill_transfersuggestion_table.py

I think in addition to modifying the pipeline to run `squad_builder:fill_initial_squad`, we can take a belt-and-braces approach, and also have the optimization script run the squad builder if someone runs it on week 1 (or a later week, if they are joining the game then).

run fill_initial_squad instead of running optimization, if next gw is 1, or no existing squad found

---

airsenal/data/duplicate_player_names.csv
airsenal/scripts/duplicate_names.py
airsenal/scripts/make_player_details.py
airsenal/scripts/replay_season.py

To avoid errors when replaying seasons, rename certain players in historic data (in player_history_wxyz.json files) to avoid confusing the data of two different players.
Creates a (manually maintained) file "duplicate_player_names.csv", which contains the IDs of players in a given season, and what they will be renamed to. By convention chosen to rename the player least likely to re-appear in FPL, and used their full name as written on Wikipedia.
Closes #351

rename certain players with duplicate names

---

airsenal/framework/season.py
airsenal/framework/utils.py
airsenal/scripts/fill_absence_table.py
airsenal/scripts/fill_db_init.py
airsenal/scripts/fill_fifa_ratings_table.py
airsenal/scripts/fill_fixture_table.py
airsenal/scripts/fill_player_attributes_table.py
airsenal/scripts/fill_player_table.py
airsenal/scripts/fill_playerscore_table.py
airsenal/scripts/fill_result_table.py
airsenal/scripts/fill_team_table.py
airsenal/scripts/scrape_transfermarkt.py
airsenal/tests/test_season.py

To address #513. Also added `--no_current_season` parser argument to determine whether or not to include `CURRENT_SEASON` which typically relies on pulling data from the various APIs - could be useful for replaying seasons.
Merged with `add-historic-absences` branch to add in new functions to create injuries and suspensions data.
Closes #513

Adding functionality to airsenal_setup_initial_db

---

airsenal/scripts/fill_transfersuggestion_table.py

Quick and hack-y fix to #555, where optimization hangs as a result of the number of strategies evaluated by the tree search not being equal to the number returned by `count_expected_outputs`, which in turn is a consequence of how we deal with the API telling us we have zero free transfers.
Fix is to set the "chip_to_play" to "wildcard" and "num_free_transfers" to 1, for this specific gameweek (22/23 season, gameweek 17).
Will revisit actual case of zero free transfers later - see discussion on #555 for more detail.

give free wild card for gw following 2022 world cup

---

airsenal/scripts/squad_builder.py

Highlighted in #559, we can get `No module named 'pygmo'`. In https://github.com/alan-turing-institute/AIrsenal/issues/495#issuecomment-1212111173, @jack89roberts noted it wasn't possible to get that error anymore. But from adding in more type-hints in #544, I re-introduced this errror as I imported pygmo to make the appropriate type-hint.
This PR fixes this by:
- removing possibility to pass in `uda` argument which was an optional `pygmo.sga` type
- passing in new argument `num_generations` which defaults to 100
- if `algorithm = "genetic"`, it attempts to use `pygmo` with `num_generations` argument, else it defaults to using `algorithm = "normal"` and sets `uda=None`

Avoid pygmo not found error if not installed (again)

---

airsenal/framework/schema.py

For #567.
Note that will need to start a new database by running `airsenal_setup_initial_db --clean` first.

add xg, xa, xgi, xgc data to player score

---

airsenal/data/fifa_team_ratings_1718.csv
airsenal/framework/bpl_interface.py

Closes issue #580 
Data collected from https://www.fifaindex.com/teams/ for the 10th August (2017) which should be just before the start of the 17/18 season

Add information for teams for the 17-18 season

---

airsenal/framework/optimization_transfers.py
airsenal/framework/optimization_utils.py
airsenal/scripts/airsenal_run_pipeline.py
airsenal/scripts/fill_transfersuggestion_table.py
airsenal/scripts/replay_season.py
airsenal/tests/test_optimization.py

Updates the optimisation code so that:
- Up to 5 free transfers can be saved in the logic around computing points hits and dropping strategies that leave transfers unused.
- I think the current main branch would actually raise an error if a user has saved more than 2 transfers, as we sanity-checked for free transfers being 0, 1, or 2 before. At minimum it would incorrectly compute points hits in cases where a user had saved more than 2 transfers.
- Adds `max_opt_transfers` and `max_free_transfers` to various optimisation functions:
- `max_free_transfers` is the maximum allowable free transfers in the game rules (now 5).
- `max_opt_transfers` is the maximum number of transfers to allow the optimisation to make each week. This still defaults to 2. At the command line the value of …

Update max free transfers to 5

---

airsenal/framework/utils.py

Tweaks start of season minutes estimation to use average of minutes played in whole of last season (what AIrsenal used in first few seasons) and minutes played in last 10 games of the previous season (what AIrsenal used in last couple of seasons). Aiming to be a better balance between players that were injured at the end of the season and players that genuinely lost their place at the end of the season.

include mins from whole season in estimate_minutes_from_prev_season

---

airsenal/framework/bpl_interface.py
airsenal/scripts/airsenal_run_pipeline.py
airsenal/scripts/fill_playerscore_table.py
airsenal/scripts/fill_predictedscore_table.py
airsenal/scripts/replay_season.py
airsenal/scripts/set_env.py
airsenal/scripts/tune_team_time_weighting.py
airsenal/tests/test_score_predictions.py
uv.lock

Based on predicting 5 game weeks ahead, with 3 seasons of previous data in the database, epsilon = 1.5 (the team model time weighting) seems to be the best compromise across the last 5 seasons. It makes very little difference overall though (0.3% improvement in the predicted probability of the actual scoreline on average, but sometimes worse and sometimes better). It means about 80% of the total weighting will be given to matches within the last year.
Fitted team strengths (Left: epsilon=0, Right: epsilon=1.5):
The epsilon=0 one looks better to me... And from a quick check the FIFA team ratings have quite a big impact for the epsilon=1.5 one, in particular. Not using the FIFA ratings but including more history in the database could be another thing to try...

Set default team model time weighting to 1.5

---

airsenal/scripts/fill_absence_table.py

- Add automatic main entry in fill_db_init.py so running the script will append --clean and call main(), enabling automatic clean database initialization.
- Import sys to support argv modification.
- Simplify CSV loading in fill_absence_table.py by removing the deprecated infer_datetime_format argument from pd.read_csv.

fix(scripts): removing the deprecated infer_datetime_format argument
