airsenal/framework/data_fetcher.py, airsenal/framework/optimization_utils.py
Fix associated with #91, may also be related to/solve #85. 
I have replicated the problem and verified that the suggested fix solves it, but not looked at the root cause.
=> order transactions in get_starting_team

.travis.yml
This may help fix #106, please let me know if this helps at all.
=> Add initial build matrix to Travis CI config

airsenal/scripts/plot_league_standings.py
Updates names and keys to reflect changed data structure returned by FPL API.
Closes #102
=> Fix airsenal_plot

README.md, airsenal/scripts/data_sanity_checks.py, setup.py
=> Entry point for data sanity checks

airsenal/framework/api_utils.py, airsenal/tests/test_api_utils.py, airsenal/tests/test_fetcher.py, airsenal/tests/test_optimization.py
api_utils API (get_session_players) had changed to return dict rather than just player_id.
Needed to update tests and some other functions to take account of this.
=> fixes to api_utils

airsenal/framework/team.py, airsenal/scripts/run_airsenal_pipeline.sh, requirements.txt
Replaces creation of FPLDataFetcher for each call of sale price function by using fetcher from utils instead.
Note this is failing on travis but master branch is also failing, seems something has changed. See #150 for details.
Closes #146
=> Reduce number of API calls made during optimisation

airsenal/framework/player.py, airsenal/framework/team.py, airsenal/tests/test_optimization.py, airsenal/tests/test_team.py
=> Order subs by expected points

airsenal/api/app.py, airsenal/framework/api_utils.py, airsenal/framework/utils.py
@nbarlowATI - should we merge the fixes you added here straight to master so builds pass on the master branch?
Edit: Ah, seems builds are not passing here either. I'll have a look at some point.
=> Fixture probability fixes

airsenal/framework/optimization_utils.py, airsenal/framework/team.py, airsenal/scripts/fill_transfersuggestion_table.py
For #185 - will merge this PR with the bench boost one later this week.
=> Add triple captain

README.md, airsenal/data/results_1819.csv, airsenal/data/results_1819_with_gw.csv
=> Fix date format in 1819 results files to match other seasons

airsenal/framework/optimization_utils.py, airsenal/framework/team.py, airsenal/framework/utils.py, airsenal/scripts/fill_transfersuggestion_table.py, airsenal/tests/test_attributes.py, airsenal/tests/test_optimization.py, airsenal/tests/test_team.py
=> Add bench boost and triple captain as optimisation options

airsenal/framework/utils.py
Does the suggestion in #82 - use zero minutes played at the start of the season for predicted points of players that moved clubs.
Also removes the hack of estimating minutes from FPL price for players that didn't play last season.
=> [#82] Zero minutes played for players who switched clubs at start of season

airsenal/tests/fixtures.py, airsenal/tests/test_team.py
Added the 'quick fix' as proposed in the #209 by changing the value of season in fixtures.py and the value of TEST_SEASON to the global constant CURRENT_SEASON!
=> [#209] Added CURRENT_SEASON from framework.utils to fixtures.py and test_team.py 

airsenal/framework/optimization_utils.py, airsenal/framework/utils.py, airsenal/scripts/fill_transfersuggestion_table.py
- Adds --profile flag to dump profile stats of `process_strat` function
- Replace usage `copy.deepcopy` with `pickle.dumps/loads`
- Cache `get_predicted_points_for_player`
For #255
=> Improve speed of fill_transfersuggestion_table

airsenal/scripts/update_results_transactions_db.py
Refactor `update_results_transactions_db.py` and add a new function that compares the list of players from the api with that from the db, and if there are any new ones from the api, add new rows to the player table in the db.
Closes #279
=> add function to add players to db that have recently been added to FPL

requirements.txt
See if initialisation errors disappear on current develop branch but with Travis pinned to 0.0.4.
See #303
=> BPL pinned to 0.0.4

airsenal/framework/optimization_utils.py, airsenal/scripts/fill_transfersuggestion_table.py
For #148 - Add a function that checks whether the prediction tag being used has predictions for all the gameweeks that are being optimised. If not quit with a message saying to run the prediction first.
=> Check whether predictions available before running optimisation

airsenal/scripts/airsenal_run_pipeline.py, airsenal/scripts/make_transfers.py, airsenal/scripts/update_db.py
but see #393 - should fix this properly
=> fix error caused by comparing int and str fpl_team_id

airsenal/framework/schema.py, airsenal/scripts/airsenal_run_pipeline.py, airsenal/scripts/fill_db_init.py
And add `--clean` argument to `airsenal_setup_initial_db` to force delete and recreate if desired
=> [#380] Check whether a database already exists before database setup

README.md, airsenal/scripts/make_transfers.py
- Changes transfer call, dictionary names used for transfer prices and elements. 
- changed PrettyTable to use get_player_from_api_id instead of get_player_name
=> addresses issue #410

airsenal/scripts/make_transfers.py
**ISSUE SOLVED**
This PR solves issue #428 
**Changes Made**
1. Modified `make_transfers.py` as discussed [here.](https://github.com/alan-turing-institute/AIrsenal/issues/428)
2. File modified: `airsenal/scripts/make_transfers.py` at 2 locations:
- added `import` statement importing `set_lineup` function from `airsenal/scripts/airtable.py`
- called the `set_lineup()` function after the `make_transfers()` function
**NOTE**
Please consider this as a submission towards **Hacktoberfest 2021** and add the `hacktoberfest-accepted` label to it.
=> fixes issue #428

README.md, airsenal/scripts/fill_transfersuggestion_table.py, airsenal/scripts/squad_builder.py
This resolves #457. I also checked other functions to see if there were any other inconsistencies but did not see any. Let me know if these changes look good or if I should change anything.
=> [Ready for review] Fix Issue #457

airsenal/framework/optimization_transfers.py
=> [#469] Avoid squad incomplete errors if no valid replacement found

airsenal/framework/data_fetcher.py
Taking approach from amosbastian/fpl: https://github.com/amosbastian/fpl/tree/d372c8d2675506dfba070622e4e0790e81161872/fpl
Closes #475
=> [#475] Update headers to fix login error

airsenal/__init__.py, requirements.txt
See https://github.com/scrapinghub/dateparser/pull/1046
Closes #479
=> [#479] Update dateparser

airsenal/framework/multiprocessing_utils.py, airsenal/framework/optimization_pygmo.py, airsenal/framework/optimization_transfers.py, airsenal/framework/optimization_utils.py, airsenal/framework/player.py, airsenal/framework/squad.py, airsenal/framework/utils.py, airsenal/scripts/airsenal_run_pipeline.py, airsenal/scripts/fill_predictedscore_table.py, airsenal/scripts/fill_transfersuggestion_table.py, airsenal/scripts/make_transfers.py, airsenal/scripts/replay_season.py, airsenal/scripts/squad_builder.py, airsenal/tests/test_optimization.py
Successfully managed to run the squad generation then GW2 transfer optimisation for the 19/20 season with this. 
Notes:
- Should update test data to check this & prediction on previous seasons to make sure everything propagated correctly
- 20/21 season get errors due to duplicate Ben Davies (in prediction) - see #351 , but works for 19/20
- Should fill database with older seasons for this (e.g. if we usually use last 3 seasons of data,  we should have 3 seasons of data before the season we're optimising for)
=> Run optimisation on previous seasons

airsenal/scripts/make_transfers.py
Closes #507 
In `make_transfers.py` separate out the priced transfer list into transfers in and transfers out, and sort each list by position, before recombining them.
=> sort transfers by position (e.g. for after wildcard)

README.md, airsenal/scripts/get_transfer_suggestions.py, airsenal/scripts/make_transfers.py, pyproject.toml
=> Recent Development

airsenal/scripts/airsenal_run_pipeline.py, airsenal/scripts/data_sanity_checks.py, airsenal/scripts/duplicate_names.py, airsenal/scripts/fill_absence_table.py, airsenal/scripts/fill_db_init.py, airsenal/scripts/fill_fifa_ratings_table.py, airsenal/scripts/fill_fixture_table.py, airsenal/scripts/fill_player_attributes_table.py, airsenal/scripts/fill_player_mappings_table.py, airsenal/scripts/fill_player_table.py, airsenal/scripts/fill_playerscore_table.py, airsenal/scripts/fill_predictedscore_table.py, airsenal/scripts/fill_result_table.py, airsenal/scripts/fill_team_table.py, airsenal/scripts/fill_transfersuggestion_table.py, airsenal/scripts/make_player_details.py, airsenal/scripts/make_player_history_table.py, airsenal/scripts/make_player_summary.py, airsenal/scripts/make_transfers.py, airsenal/scripts/match_player_names.py, airsenal/scripts/match_team_names.py, airsenal/scripts/replay_season.py, airsenal/scripts/scrape_transfermarkt.py, airsenal/scripts/set_lineup.py, airsenal/scripts/squad_builder.py, airsenal/scripts/update_db.py
Partially addressing #526 - added type hints for `fill_*` and `make_*` scripts in `airsenal/scripts`.
=> Type hints for scripts

airsenal/scripts/fill_player_mappings_table.py
Update to use `List` from [`typing`](https://docs.python.org/3/library/typing.html) to fix error in #559.
=> Fix for #559

airsenal/framework/data_fetcher.py, airsenal/framework/optimization_utils.py, airsenal/framework/squad.py, airsenal/framework/utils.py, airsenal/scripts/airsenal_run_pipeline.py, airsenal/scripts/make_transfers.py, airsenal/scripts/set_lineup.py
=> Fix #608 logging in issue

airsenal/scripts/get_transfer_suggestions.py, airsenal/scripts/make_transfers.py, pyproject.toml
=> AIrsenal 1.7.2

airsenal/scripts/airsenal_run_pipeline.py
=> Allow --max_transfers, --max_hit and --allow_unused options for airsenal_run_pipeline

Dockerfile
Fixes issue https://github.com/alan-turing-institute/AIrsenal/issues/710
=> fix(docker): update base image from buster to bullseye
